name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Go 1.19
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.19

      - name: Cache Go modules
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Get release tag
        if: github.event_name == 'release'
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Go binary amd64
        run: go build -ldflags "-s -w -X main.GitCommit=$GITHUB_SHA -X main.GitRef=$GITHUB_REF -X main.Version=${RELEASE_TAG:-commit-$GITHUB_SHA}" -o bin/castai-agent-amd64 .
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Build Go binary arm64
        run: go build -ldflags "-s -w -X main.GitCommit=$GITHUB_SHA -X main.GitRef=$GITHUB_REF -X main.Version=${RELEASE_TAG:-commit-$GITHUB_SHA}" -o bin/castai-agent-arm64 .
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0

      - name: Test
        run: go test -race ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

      - name: Login to Google Artifact Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_BUILDER_JSON_KEY }}

      - name: Build and push main
        if: github.event_name != 'release'
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64,linux/amd64
          tags: us-docker.pkg.dev/castai-hub/library/agent:${{ github.sha }}

      - name: Build and push main RedHat UBI
        if: github.event_name != 'release'
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          file: ./redhat/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64,linux/amd64
          tags: us-docker.pkg.dev/castai-hub/library/agent-rh-ubi:${{ github.sha }}

      - name: Build and push release
        if: github.event_name == 'release'
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            us-docker.pkg.dev/castai-hub/library/agent:${{ env.RELEASE_TAG }}
            us-docker.pkg.dev/castai-hub/library/agent:latest

      - name: Build and push release RedHat UBI
        if: github.event_name == 'release'
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          file: ./redhat/Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            us-docker.pkg.dev/castai-hub/library/agent-rh-ubi:${{ env.RELEASE_TAG }}
            us-docker.pkg.dev/castai-hub/library/agent-rh-ubi:latest

      - name: Docker pull for fossa main
        if: github.event_name == 'release'
        run: docker pull us-docker.pkg.dev/castai-hub/library/agent:${{ env.RELEASE_TAG }}

      - name: Docker pull for fossa main RedHat UBI
        if: github.event_name == 'release'
        run: docker pull us-docker.pkg.dev/castai-hub/library/agent-rh-ubi:${{ env.RELEASE_TAG }}

      - name: FOSSA scan docker image
        if: github.event_name == 'release'
        uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f # v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          container: us-docker.pkg.dev/castai-hub/library/agent:${{ env.RELEASE_TAG }}

      - name: FOSSA scan docker image RedHat UBI
        if: github.event_name == 'release'
        uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f # v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          container: us-docker.pkg.dev/castai-hub/library/agent-rh-ubi:${{ env.RELEASE_TAG }}
