---
# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 'latest'
    - name: Build
      run: |
        go build ./...

    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: preZero Static Analysis
      run: |
        ${GITHUB_WORKSPACE}/sl --version
        ${GITHUB_WORKSPACE}/sl analyze --strict --wait \
          --app Kubectl-k8s-agent \
          --tag branch=${{ github.head_ref }} \
          --go $(pwd)
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

#   Build-Rules:
#     runs-on: ubuntu-latest
#     permissions: write-all
#     needs: NextGen-Static-Analysis
#     steps:
#     - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
#     - name: Download ShiftLeft CLI
#       run: |
#         curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
#     - name: Validate Build Rules
#       run: |
#         ${GITHUB_WORKSPACE}/sl check-analysis --app Kubectl-k8s-agent \
#             --github-pr-number=${{github.event.number}} \
#             --github-pr-user=${{ github.repository_owner }} \
#             --github-pr-repo=${{ github.event.repository.name }} \
#             --github-token=${{ secrets.GITHUB_TOKEN }}
#       env:
#         # SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
#
#         SHIFTLEFT_API_HOST: www.shiftleft.io
#         SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
#         SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
#


